gitbox_application:
    resource: "@GitboxApplicationBundle/Resources/config/routing.yml"
    prefix:   /

AcmeHelloWorldBundle:
    resource: "@AcmeHelloWorldBundle/Resources/config/routing.yml"
    prefix:   /
