parameters:
#    gitbox_application.example.class: Gitbox\ApplicationBundle\Example

services:
#    gitbox_application.example:
#        class: %gitbox_application.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
