imports:
    - { resource: "@GitboxCoreBundle/Resources/config/services.yml" }

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
    template:
        pagination: GitboxCoreBundle:Pagination:twbs_v3_pagination.html.twig