parameters:
    user_helper.class: Gitbox\Bundle\CoreBundle\Helper\UserAccountHelper
    mailer_helper.class: Gitbox\Bundle\CoreBundle\Helper\MailerHelper
    module_helper.class: Gitbox\Bundle\CoreBundle\Helper\ModuleHelper
    blog_content_helper.class: Gitbox\Bundle\CoreBundle\Helper\BlogContentHelper
    tube_content_helper.class: Gitbox\Bundle\CoreBundle\Helper\TubeContentHelper
    permissions_helper.class: Gitbox\Bundle\CoreBundle\Helper\PermissionsHelper

services:
    user_helper:
        class:        "%user_helper.class%"
        arguments:    ["@doctrine.orm.entity_manager"]
    mailer_helper:
        class:        "%mailer_helper.class%"
        arguments:    ["@mailer"]
    module_helper:
        class:        "%module_helper.class%"
        arguments:    ["@doctrine.orm.entity_manager"]
    blog_content_helper:
        class:        "%blog_content_helper.class%"
        arguments:    ["@doctrine.orm.entity_manager"]
    tube_content_helper:
        class:        "%tube_content_helper.class%"
        arguments:    ["@doctrine.orm.entity_manager"]
    permissions_helper:
        class:        "%permissions_helper.class%"
        arguments:    ["@session"]
