parameters:
    user_helper.class: Gitbox\Bundle\CoreBundle\Helper\UserAccountHelper
    user_description.class: Gitbox\Bundle\CoreBundle\Helper\UserDescriptionHelper
    mailer_helper.class: Gitbox\Bundle\CoreBundle\Helper\MailerHelper
    module_helper.class: Gitbox\Bundle\CoreBundle\Helper\ModuleHelper
#    blog_content_helper.class: Gitbox\Bundle\CoreBundle\Helper\BlogContentHelper
    tube_content_helper.class: Gitbox\Bundle\CoreBundle\Helper\TubeContentHelper
    menu_helper.class: Gitbox\Bundle\CoreBundle\Helper\MenuHelper
    permissions_helper.class: Gitbox\Bundle\CoreBundle\Helper\PermissionsHelper
    user_activities_helper.class: Gitbox\Bundle\CoreBundle\Helper\UserActivitiesHelper
    fav_content_helper.class: Gitbox\Bundle\CoreBundle\Helper\FavContentHelper
    cache_helper.class: Gitbox\Bundle\CoreBundle\Helper\CacheHelper
    ip_helper.class: Gitbox\Bundle\CoreBundle\Helper\IPHelper
    cache_helper.host: localhost
    cache_helper.port: 11211

services:
    user_helper:
        class:        "%user_helper.class%"
        arguments:    ["@doctrine.orm.entity_manager", "@cache_helper"]
    user_description_helper:
        class:        "%user_description.class%"
        arguments:    ["@doctrine.orm.entity_manager", "@cache_helper"]
    mailer_helper:
        class:        "%mailer_helper.class%"
        arguments:    ["@mailer"]
    module_helper:
        class:        "%module_helper.class%"
        arguments:    ["@doctrine.orm.entity_manager", "@cache_helper"]
    drive_content_helper:
        class:        Gitbox\Bundle\CoreBundle\Helper\DriveContentHelper
        arguments:    ["@doctrine.orm.entity_manager", "@cache_helper"]
    blog_content_helper:
        class:        Gitbox\Bundle\CoreBundle\Helper\BlogContentHelper
        arguments:    ["@doctrine.orm.entity_manager", "@cache_helper"]
        tags:
            - { name: knp_paginator.injectable, paginator: knp_paginator }
    tube_content_helper:
        class:        "%tube_content_helper.class%"
        arguments:    ["@doctrine.orm.entity_manager", "@cache_helper"]
    menu_helper:
        class:        "%menu_helper.class%"
        arguments:    ["@doctrine.orm.entity_manager", "@cache_helper"]
    permissions_helper:
        class:        "%permissions_helper.class%"
        arguments:    ["@session", "@doctrine.orm.entity_manager", "@cache_helper"]
    dp_helper:
        class:        Gitbox\Bundle\CoreBundle\Helper\DrivePermissionHelper
        arguments:    ["@session"]
    user_activities_helper:
        class:        "%user_activities_helper.class%"
        arguments:    ["@doctrine.orm.entity_manager", "@cache_helper", "@doctrine.dbal.default_connection"]
    fav_content_helper:
        class:        "%fav_content_helper.class%"
        arguments:    ["@doctrine.orm.entity_manager", "@cache_helper"]
    cache_helper:
        class:        "%cache_helper.class%"
        arguments:    ["@doctrine.orm.entity_manager", "%cache_helper.host%", "%cache_helper.port%"]
    ip_helper:
        class:        "%ip_helper.class%"
        arguments:    ["@doctrine.orm.entity_manager", "@cache_helper"]
