parameters:
    user_helper.class: Gitbox\Bundle\CoreBundle\Helper\UserAccountHelper
    mailer_helper.class: Gitbox\Bundle\CoreBundle\Helper\MailerHelper
    module_helper.class: Gitbox\Bundle\CoreBundle\Helper\ModuleHelper
    blog_content_helper.class: Gitbox\Bundle\CoreBundle\Helper\BlogContentHelper
    permission_helper.class: Gitbox\Bundle\CoreBundle\Helper\PermissionHelper

services:
    user_helper:
        class:        "%user_helper.class%"
        arguments:    ["@doctrine.orm.entity_manager"]
    mailer_helper:
        class:        "%mailer_helper.class%"
        arguments:    ["@mailer"]
    module_helper:
        class:        "%module_helper.class%"
        arguments:    ["@doctrine.orm.entity_manager"]
    blog_content_helper:
        class:        "%blog_content_helper.class%"
        arguments:    ["@doctrine.orm.entity_manager"]
    permission_helper:
        class:        "%permission_helper.class%"
        arguments:    ["@session"]